uni_web_noticias_homepage:
    path:     /hello/{name}
    defaults: { _controller: uniWebNoticiasBundle:Default:index }
    
uni_web_noticias_inicio:
    path:     /home
    defaults: { _controller: uniWebNoticiasBundle:Default:home }

uni_web_noticias_not:
    path:     /contenidos/{titulo}/{texto}/{autor}/{foto}
    defaults: { _controller: uniWebNoticiasBundle:Noticias:mostrarNoticia }
    
uni_web_noticias_about:
    path:     /contenidos/about
    defaults: { _controller: uniWebNoticiasBundle:Noticias:mostrarAbout }